name: Snapyr Publish Artifact

on:
  push:
    branches: [ main ]

jobs:

  publish_snapshot:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Configure
        run: |
          echo ${SIGNING_SECRET_KEY_RING_FILE_DATA} | base64 --decode > /tmp/key_ring.gpg
      - name: Publish snapshot
        run: ./gradlew publish -Prelease
        env:
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_SECRET_KEY_RING_FILE: /tmp/key_ring.gpg
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}



